version: "3.9"

services:
  frontend:
    build: ./frontend # Path to dockerfile
    ports: # Port binding to host from docker container
      - "80:3000" # Bind port 80 of host to 3000 of container
    restart: always # What to do if container crashes
    container_name: frontend
    networks:
      - mynetwork

  # Create backend container
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:3000"
    container_name: backend-docker
    restart: always
    networks:
      - mynetwork

  # Create database container
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    container_name: database-docker
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork: